# Generated by Django 6.0.6 on 2026-07-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_merge_0003_auto_20210726_1109_0003_auto_20210727_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
