# Generated by Django 6.0.6 on 2026-07-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
